-- require("lazy-lua.config.lazy")

require("chitthaenaing.plugins-setup")
require("chitthaenaing.plugins.comment")
require("chitthaenaing.plugins.nvim-tree")
require("chitthaenaing.plugins.telescope")
require("chitthaenaing.plugins.lualine")
require("chitthaenaing.plugins.nvim-cmp")
require("chitthaenaing.plugins.lsp.mason")
require("chitthaenaing.plugins.lsp.lspsaga")
require("chitthaenaing.plugins.lsp.lspconfig")
require("chitthaenaing.plugins.lsp.null-ls")
require("chitthaenaing.plugins.autopairs")
require("chitthaenaing.plugins.treesitter")
require("chitthaenaing.plugins.gitsigns")
require("chitthaenaing.core.options")
require("chitthaenaing.core.keymaps")
require("chitthaenaing.core.colorscheme")
